server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialNetwork
    username: root
    password: Hars30896@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true